#!/usr/bin/env ruby

# Trap ^C
Signal.trap("INT") {
  puts "\nCtrl-C detected. Exiting..."
  sleep 1
  exit
}

$:.unshift(File.expand_path("../../lib", __FILE__))
require "foodie"
require "foodie/cli"

Foodie::CLI.start(ARGV)
